spring:
  application:
    name: kiosk-tabling-services
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3307/kiosk_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zerobase
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ???? (?? ????? none?? ?? ??)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  data:
    redis:
      host: localhost
      port: 6378

server:
  port: 8080


